safe:        false
port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins

paginate: 5

domain: www.heathanderson.net

exclude: 
  - rakefile.rb
future:      true
lsi:         false
pygments:    true
markdown:    redcarpet
permalink: /:year/:month/:day/:title

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

redcarpet:
  extensions: ["no_intra_emphasis"]

rdiscount:
  extensions: []

sass:
    syntax: scss        # scss|sass
    style:  compressed  # nested|expanded|compact|compressed