safe:        false
auto:        false
server:      false
server_port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins

paginate: 10

domain: www.heathanderson.net

exclude: rakefile.rb
future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink: /:year/:month/:day/:title

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []